application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  # Value retrieves from Email Provider's API documentation
  base_url: "https://api.postmarkapp.com"
  # Use the single sender email you authorised on Email Provider's  (Example: Postmark)
  sender_email: "Something@gmail.com"
